version: '3.4'

services:
  taskbot:
    build: .
    image: "${REGISTRY_NAME}devclubiitd/taskbot:0.1"
    working_dir: /app
    volumes:
      - tinydb:/db/
    env_file:
      - ./.env
    restart: always
    networks:
      - "reverseproxy"
      - "internal"

volumes:
  tinydb:

networks:
  reverseproxy:
    external:
      name: "reverseproxy"
  internal: